version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/**",
  "**/dist/**",           
  "**/*.min.js",        
  "vite.config.js"        
]


[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react", "eslint-plugin-react"]
module_system = "es-modules"
environment = ["nodejs", "browser"]
dialect = "typescript"
skip_doc_coverage = ["class-expression", "method-definition"]
cyclomatic_complexity_threshold = "high"
style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true
