version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/**",
  "**/dist/**",
  "**/*.min.js",
  "vite.config.js"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  module_system = "es-modules"
  plugins = [
    "react",
    "eslint-plugin-react"
  ]
  environment = [
    "nodejs",
    "browser",
    "vitest"
  ]
  skip_doc_coverage = ["class-expression", "method-definition"]
  cyclomatic_complexity_threshold = "high"
  style_guide = "airbnb"

[[transformers]]
name = "prettier"